### ISSUE TITLE
附录C中有几个数学公式建议改成网络图片的格式

### ISSUE THREAD

**Issue by lon91ong** [songjinghe/TYS-zh-translation#5]
现在的那几个公式直接用了latex公式代码表示, 未经编译可读性太差
有网站提供在线的latex公式编译服务, 直接在网址中提交公式, 返回编译后的公式图片
比如:
http://latex.codecogs.com/gif.latex?$e^{\mathrm{i}x}=\cos%20x+\mathrm{i}\sin%20x$
建议用这个

**Comment by songjinghe** [comment]
谢谢你～我还不知道有这么好的网站：）

我认为对于纯markdown来说，直接用latex代码或者嵌入你说的那么长一串网址的可读性都比较差～

另外我看了一下至少在github上纯markdown中嵌入的图片也是不显示的，比如附录C中积分的那个[示意图](https://github.com/songjinghe/TYS-zh-translation/blob/master/400-appendix-c-numerical-techniques.md)里面就有一个坏掉的图片链接（链接本身是好的，但是github处理后就不能正常显示了）。

而在我提供的html在线版本上，我使用了mathjax来显示其中的公式，这样就没有问题了。
